name: gh-pages

on:
  workflow_dispatch: # add manually button
  repository_dispatch:
    types: [gh-pages]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  gh-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Install and run V2Ray
        run: |
          wget -O v2ray.zip https://github.com/v2fly/v2ray-core/releases/download/v5.7.0/v2ray-linux-64.zip
          unzip v2ray.zip -d v2ray
          cd v2ray
          echo ${{ secrets.V2RAY_CONFIG_BASE64 }} | base64 -d > config.json
          nohup ./v2ray run &
          cd ..

      - name: Run Spider
        uses: gradle/gradle-build-action@v2
        env:
          JSESSIONID: ${{ secrets.JSESSIONID }}
          HTTP_PROXY: http://127.0.0.1:1080
          HTTPS_PROXY: http://127.0.0.1:1080
        with:
          arguments: |
            run

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./build/html"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
